### ISSUE TITLE
Criar conversor de comprimento

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#1]
**Descrição:**
Desenvolver o módulo para conversão de unidades de comprimento (metros, centímetros, milímetros).

**Requisitos:**
- Criar o arquivo `comprimento.c` em `src/`.
- Criar o arquivo `comprimento.h` em `include/`.
- Implementar as funções descritas no tutorial.

**Branch sugerida:** `feature/comprimento`.

**Checklist:**
- [ ] Código desenvolvido.
- [ ] Testado e funcionando corretamente.
- [ ] Revisado e aprovado.

**Comment by MatheusMatos98** [comment]
complementação do conversor de comprimento concluído
