### ISSUE TITLE
Testes e depuração do projeto

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#10]
Esta tarefa envolve a criação de testes automatizados para garantir que todas as funcionalidades de conversão estão funcionando corretamente. Também é necessário depurar quaisquer erros que possam surgir durante a execução do projeto.

Requisitos:

- Criar testes unitários para cada conversor.
- Testar todas as funcionalidades.
- Depurar erros e falhas que forem encontrados.

**Comment by CaioBrun0** [comment]
Os testes foram feitos com o Unity.
