### ISSUE TITLE
Criar conversor de massa (quilograma, grama, tonelada)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#2]
A tarefa é criar um conversor de unidades de massa. O conversor deverá permitir conversões entre quilograma, grama e tonelada.

Requisitos:

- Permitir entrada para quilograma, grama e tonelada.
- Implementar funções para conversão entre essas unidades.
- Validar as entradas e tratar erros adequadamente.

**Comment by Vivian-RC** [comment]
Implementação do conversor de massa concluído.
