### ISSUE TITLE
Criar conversor de volume (litro, mililitro, metros cúbicos)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#3]
O objetivo desta tarefa é criar um conversor para unidades de volume. O sistema deverá permitir conversões entre litro, mililitro e metros cúbicos.

Requisitos:

- Aceitar valores em litro, mililitro e metros cúbicos.
- Implementar funções de conversão entre essas unidades.
- Garantir a validação das entradas e tratar possíveis erros.

**Comment by Daniel24060** [comment]
Implementação conversor de volume concluído.
