### ISSUE TITLE
Criar conversor de temperatura (Celsius, Fahrenheit, Kelvin)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#4]
A tarefa envolve a criação de um conversor de temperatura. O conversor deve permitir que os valores de temperatura sejam convertidos entre Celsius, Fahrenheit e Kelvin.

Requisitos:

- Permitir entrada para Celsius, Fahrenheit e Kelvin.
- Implementar funções para conversão entre as unidades de temperatura.
- Garantir que as entradas sejam válidas e tratar erros.

**Comment by joelson-santana22** [comment]
Implementação do conversor de temperatura concluída.
