### ISSUE TITLE
Criar conversor de velocidade (km/h, m/s, mph)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#5]
Esta tarefa é para implementar um conversor de unidades de velocidade. As unidades que o sistema deve ser capaz de converter são km/h, m/s e mph.

Requisitos:

- Aceitar entradas para km/h, m/s e mph.
- Implementar funções para conversão entre essas unidades de velocidade.
- Validar entradas e tratar erros.

**Comment by mychaelmatos** [comment]
Implementação do conversor de velocidade concluído.
