### ISSUE TITLE
Criar conversor de potência (Watts, quilowatts, cavalos-vapor)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#6]
A tarefa é criar um conversor de potência. O sistema deve permitir conversões entre as unidades de Watts, quilowatts e cavalos-vapor.

Requisitos:

- Permitir entradas para Watts, quilowatts e cavalos-vapor.
- Implementar funções para conversão entre essas unidades de potência.
- Validar entradas e tratar erros.

**Comment by Ericfranco0** [comment]
Implementação do conversor de potência concluído.
