### ISSUE TITLE
Criar conversor de área (metro quadrado, centímetro quadrado)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#7]
Esta tarefa é responsável pela criação de um conversor de área. O sistema deve permitir conversões entre metro quadrado e centímetro quadrado.

Requisitos:

- Receber entradas para metro quadrado e centímetro quadrado.
- Implementar funções de conversão entre essas unidades.
- Garantir a validação das entradas e tratar erros.

**Comment by CaioBrun0** [comment]
Implementação de conversor de área concluído.
