### ISSUE TITLE
Criar conversor de tempo (segundos, minutos, horas)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#8]
O objetivo desta tarefa é implementar um conversor de tempo, permitindo a conversão entre segundos, minutos e horas.

Requisitos:

- Aceitar entradas para segundos, minutos e horas.
- Implementar as funções necessárias para conversão entre essas unidades de tempo.
- Validar as entradas e tratar erros.

**Comment by mychaelmatos** [comment]
Implementação conversor de tempo concluído.
