### ISSUE TITLE
Criar conversor de dados (bits, bytes, KB, MB, GB, TB)

### ISSUE THREAD

**Issue by adimael** [adimael/conversor-unidades#9]
Esta tarefa envolve a criação de um conversor de unidades de dados. O sistema deve ser capaz de converter entre bits, bytes, kilobytes (KB), megabytes (MB), gigabytes (GB) e terabytes (TB).

Requisitos:

- Permitir entradas para bits, bytes, KB, MB, GB e TB.
- Implementar funções para conversão entre essas unidades.
- Validar entradas e tratar erros.

**Comment by SauloDavi28** [comment]
implementação do conversor de dados concluído.
